version: '3'
logger:
  dir: ./logs
  is_debug: false
  is_development: false

grpc:
  port: 50051

store:
  port: 5432
  host: localhost
  user: pq_user
  password: superpass
  database: postgres

jwt-secret: <very-secret-secret>